### ISSUE TITLE
Synthethis Keeps Giving Me Error NU1202, Please Help!

### ISSUE THREAD

**Issue by nicksws007** [Synthesis-Collective/EnemyReleveler#6]
NOTE: I'm a complete noob at Synthethis patching, and I'm just trying to patch this one single mod for Skyrim SE before I play.

Error Log is as follows:

EnemyReleveler.csproj : error NU1202: Package Newtonsoft.Json 12.0.3 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package Newtonsoft.Json 12.0.3 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package Microsoft.Win32.Registry 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package Microsoft.Win32.Registry 5.0.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package CommandLineParser 2.8.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package CommandLineParser 2.8.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package K4os.Hash.xxHash 1.0.6 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package K4os.Hash.xxHash 1.0.6 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package System.Security.AccessControl 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package System.Security.AccessControl 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package System.Security.Principal.Windows 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package System.Security.Principal.Windows 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package Newtonsoft.Json 12.0.3 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package Newtonsoft.Json 12.0.3 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package Microsoft.Win32.Registry 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package Microsoft.Win32.Registry 5.0.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package CommandLineParser 2.8.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package CommandLineParser 2.8.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package K4os.Hash.xxHash 1.0.6 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package K4os.Hash.xxHash 1.0.6 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package System.Security.AccessControl 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package System.Security.AccessControl 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package System.Security.Principal.Windows 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package System.Security.Principal.Windows 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package Newtonsoft.Json 12.0.3 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package Newtonsoft.Json 12.0.3 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package Microsoft.Win32.Registry 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package Microsoft.Win32.Registry 5.0.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package CommandLineParser 2.8.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package CommandLineParser 2.8.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package K4os.Hash.xxHash 1.0.6 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package K4os.Hash.xxHash 1.0.6 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package System.Security.AccessControl 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package System.Security.AccessControl 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package System.Security.Principal.Windows 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package System.Security.Principal.Windows 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package Newtonsoft.Json 12.0.3 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package Newtonsoft.Json 12.0.3 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package Microsoft.Win32.Registry 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package Microsoft.Win32.Registry 5.0.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package CommandLineParser 2.8.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package CommandLineParser 2.8.0 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package K4os.Hash.xxHash 1.0.6 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package K4os.Hash.xxHash 1.0.6 does not support any target frameworks.
EnemyReleveler.csproj : error NU1202: Package System.Security.AccessControl 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package System.Security.AccessControl 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)
EnemyReleveler.csproj : error NU1202: Package System.Security.Principal.Windows 5.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package System.Security.Principal.Windows 5.0.0 supports: uap10.0.16299 (UAP,Version=v10.0.16299)

Any and all help is much appreciated!

**Comment by Noggog** [comment]
https://github.com/Mutagen-Modding/Synthesis/discussions/228

**Comment by nicksws007** [comment]
> [Mutagen-Modding/Synthesis#228](https://github.com/Mutagen-Modding/Synthesis/discussions/228)

Perfect, this is exactly what I needed! Thank you very much! 😄
